version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stopcontainer.sh
      timeout: 300
      runas: root
      command: chmod +x scripts/stopcontainer.sh
  AfterInstall:
    - location: scripts/startcontainer.sh
      timeout: 300
      runas: root
      command: chmod +x scripts/startcontainer.sh
